<?php
require_once __DIR__ . '/../includes/auth.php';
require_login('employee');
$user = current_user();
$stats = db()->prepare("SELECT COUNT(*) AS total, COALESCE(SUM(status = 'pending'), 0) AS pending, COALESCE(SUM(status = 'approved'), 0) AS approved, COALESCE(SUM(CASE WHEN status = 'approved' THEN days ELSE 0 END), 0) AS used FROM leave_applications WHERE user_id = ?");
$stats->execute([$user['id']]); $stats = $stats->fetch();
$recent = db()->prepare('SELECT la.*, lt.name AS leave_type FROM leave_applications la JOIN leave_types lt ON lt.id = la.leave_type_id WHERE la.user_id = ? ORDER BY la.created_at DESC LIMIT 4');
$recent->execute([$user['id']]);
$notifications = db()->prepare('SELECT * FROM notifications WHERE user_id = ? ORDER BY created_at DESC LIMIT 3'); $notifications->execute([$user['id']]);
$pageTitle = 'Overview'; require __DIR__ . '/../includes/header.php';
?>
<div class="page-content"><div class="dashboard-intro"><div><span class="eyebrow"><?= e(date('l, F j, Y')) ?></span><h2>Welcome, <?= e(explode(' ', $user['full_name'])[0]) ?>.</h2><p class="muted mb-0">Here is the shape of your time away this year.</p></div><a class="btn btn-primary" href="<?= e(base_url('employee/apply-leave.php')) ?>">Apply for leave <span>&rarr;</span></a></div>
<div class="stats-grid"><div class="stat-card tone-mint"><div class="stat-label">Annual leave</div><div class="stat-value"><?= e((string) $user['annual_leave']) ?><small class="fs-6"> days</small></div><div class="stat-meta">Available balance</div></div><div class="stat-card tone-peach"><div class="stat-label">Sick leave</div><div class="stat-value"><?= e((string) $user['sick_leave']) ?><small class="fs-6"> days</small></div><div class="stat-meta">Available balance</div></div><div class="stat-card tone-gold"><div class="stat-label">Awaiting review</div><div class="stat-value"><?= (int) $stats['pending'] ?></div><div class="stat-meta">Open requests</div></div><div class="stat-card"><div class="stat-label">Days used</div><div class="stat-value"><?= e((string) $stats['used']) ?></div><div class="stat-meta">Approved this year</div></div></div>
<div class="content-grid"><section class="panel"><div class="panel-heading"><h3>Recent requests</h3><a class="text-link" href="<?= e(base_url('employee/leave-history.php')) ?>">View all &rarr;</a></div><table class="table"><thead><tr><th>Leave type</th><th>Dates</th><th>Duration</th><th>Status</th></tr></thead><tbody><?php while ($item = $recent->fetch()): ?><tr><td><strong><?= e($item['leave_type']) ?></strong><br><small class="muted"><?= e(date('M j, Y', strtotime($item['created_at']))) ?></small></td><td><?= e(date('M j', strtotime($item['start_date']))) ?> - <?= e(date('M j, Y', strtotime($item['end_date']))) ?></td><td><?= e((string) $item['days']) ?> <?= $item['days'] == 1 ? 'day' : 'days' ?></td><td><span class="status status-<?= e($item['status']) ?>"><?= e($item['status']) ?></span></td></tr><?php endwhile; ?></tbody></table></section><aside><section class="panel"><div class="panel-heading"><h3>Latest updates</h3><a class="text-link" href="<?= e(base_url('employee/notifications.php')) ?>">See all</a></div><div class="mini-list"><?php while ($note = $notifications->fetch()): ?><div class="mini-row"><div class="mini-icon">&#9673;</div><div><strong><?= e($note['title']) ?></strong><span><?= e($note['message']) ?></span></div></div><?php endwhile; ?></div></section><div class="balance-card"><h3>Leave at a glance</h3><div class="balance-item"><span>Annual leave</span><strong><?= e((string) $user['annual_leave']) ?> days left</strong></div><div class="balance-item"><span>Sick leave</span><strong><?= e((string) $user['sick_leave']) ?> days left</strong></div><div class="balance-item"><span>Requests submitted</span><strong><?= (int) $stats['total'] ?></strong></div></div></aside></div></div><?php require __DIR__ . '/../includes/footer.php'; ?>
